version: '3.8'

services:
  # soccer_api:
  #   container_name: 'soccer_api'
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   depends_on:
  #     - db_soccer_api
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     JWT_SECRET: 'Fx6hVj9x4SZ2fw5uZwz8KWDcTYy6uWC57vGGFYaDCNGNC3u79J'
  #     DATABASE_URL: 'postgres://soccer_api:soccer_api@db_soccer_api:5432/soccer_api'

  db_soccer_api:
    container_name: 'db_soccer_api'
    image: 'postgres:16.3-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'soccer_api'
      POSTGRES_PASSWORD: 'soccer_api'
      POSTGRES_DB: 'soccer_api'
