version: '3.8'

services:
  soccer_api:
    container_name: 'soccer_api'
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db_soccer_api
    ports:
      - '3000:3000'
    environment:
      - ENV=development
      - BASE_URL=http://localhost
      - PORT=3000
      - CARTOLA_API_URL=https://api.cartolafc.globo.com
      - JWT_SECRET=38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b
      - DATABASE_URL=postgres://soccer_api:soccer_api@db_soccer_api:5432/soccer_api

  db_soccer_api:
    container_name: 'db_soccer_api'
    image: 'postgres:16.3-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'soccer_api'
      POSTGRES_PASSWORD: 'soccer_api'
      POSTGRES_DB: 'soccer_api'
